name: test

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Compile typescript
        run: yarn verify
